# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Les annotations avec le langage Java
author: Emmanuel BRUNO
copyright: "2022" 
#logo: logo.png
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", ".book/**"]

sphinx:
  config:
    language: en

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # execute_notebooks: force
  execute_notebooks: cache
  run_in_temp: true


# Define the name of the latex output file for PDF builds
latex:
  latex_engine: xelatex
  latex_documents:
    targetname: LesAnnotationsEnJava.tex

launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org
  jupyterhub_url: https://jovem.univ-tln.fr

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ebpro/javanotebook-full  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: develop  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
